language: python
python:
  - '3.8'
install:
  - pip install -e .[test]
script:
  - python tests/manage.py test tests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: l8QKizGuFe+3grMyXEfGIB9YtZsl7yhsZ5PtEe5KMNpjBENPrESUE3GfO/Tf+XlKWfYdXgX1fqPX7Q/Ic0KKAiAjGCNPXI4psYFCZlZU4S1SlZ9PUFg53RQOhX9xxFeB/ymNpKMDfqIkHtewmleCp2PmmNKecfAkkFlbzztB7ztb5jvylj8iDERwzhODI6zW3NBHShnvgKqywHW/n0Vdfjgb2tEAi8PVlgh6h3L1gJ88gOhYSorCpTnl8dQ1DlfG0zs2gMfyzN2DuFfAidywpQ6IzRSsvBAggdO9vH+ucytaC7z6K1n1UfI6D9JJum3/e0efuS+3R8rzO+40r1oxzkeShMoNL4ZNoS7wot2qGBKRfMbO58lbIf9GHypzwJAaakLLOoBHNdlKRLXuogNy44ekPawbKg+IO0nxH2Q1rVyKaAP2beb7GCHCM3uaDGp/PNhEcQCoa0MzCemMQc6y7JFPeh7IeeA5nR/SwmovI4yY1tyS6OlkVVF5EGTO5GEoo0ZrvszxfK65g2/KslWa6XmdVrOLaiNJe96HgPJHZ9fjfX+Ai0l6F6pwM50MGpal00nuDdQlaIwr4l1ZYQ4jrF33hlB0qW27mzD4IdPAPEVJd5m3PIrEIktR6IiojythVQFEstkWphihqE8VZU6wNKvwbeKfAH5CjnO43mQ2obU=
  on:
    branch: production